version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "lpm0073"
    reviewers:
      - "lpm0073"
  - package-ecosystem: "pip"
    directory: "/requirements/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "python"
    assignees:
      - "lpm0073"
    reviewers:
      - "lpm0073"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "javascript"
    assignees:
      - "lpm0073"
    reviewers:
      - "lpm0073"
