default_language_version:
  # default language version for each language
  python: python3.8
repos:
  -   repo: https://github.com/ambv/black
      rev: 23.3.0
      hooks:
      - id: black
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      # See https://pre-commit.com/hooks.html for more hooks
      - id: check-added-large-files
        args:
        - --maxkb=128
      - id: check-docstring-first
      - id: check-json
      - id: check-xml
      - id: detect-private-key
      - id: mixed-line-ending
        args: [ '--fix=lf' ]
        description: Forces to replace line ending by the UNIX 'lf' character.
      - id: fix-encoding-pragma
      - id: name-tests-test
        args:
        - --django
        exclude: ^tests/testapp|^tests/management/|^tests/collisions/|^tests/pythonrc.py|^tests/runner.py
      - id: check-ast
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: debug-statements
      - id: end-of-file-fixer
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-yaml
      - id: debug-statements
        exclude: tests/
      - id: destroyed-symlinks
      - id: end-of-file-fixer
        exclude: tests/test_changes/
        files: \.(py|sh|rst|yml|yaml)$
      - id: trailing-whitespace
        files: \.(py|sh|rst|yml|yaml)$
  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        additional_dependencies: [
            'flake8-blind-except',
            'flake8-bugbear',
            'flake8-comprehensions',
            'flake8-docstrings',
            'flake8-implicit-str-concat',
            'pydocstyle',
            'flake8-coding',
            'flake8-debugger',
            'flake8-deprecated',
            'flake8-pep3101',
            'flake8-polyfill',
            'flake8-print',
            'flake8-string-format',
        ]
        exclude: ^tests/test_cases/no_closing_bracket\.py$
  - repo: https://github.com/rstcheck/rstcheck
    rev: v6.1.1
    hooks:
      - id: rstcheck
        args: [
            --report-level=warning,
        ]
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.4
    hooks:
      - id: codespell
        files: \.(py|sh|rst|yml|yaml)$
  - repo: https://github.com/trbs/pre-commit-hooks-trbs.git
    rev: 1.2.4
    hooks:
      - id: forbid-executables
        exclude: manage.py|setup.py
