#---------------------------------------------------------
# - Create a semantical release
# - Set latest tag
#---------------------------------------------------------
name: Create a new release

on:
  workflow_dispatch:
  push:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # required antecedent
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '16'

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        id: semantic
        with:
          branches: |
            [
              '+([0-9])?(.{+([0-9]),x}).x',
              'main',
              'next',
              'next-major',
              {
                name: 'beta',
                prerelease: true
              },
              {
                name: 'alpha',
                prerelease: true
              }
            ]
          extra_plugins: |
            @semantic-release/git
            @semantic-release/changelog
        env:
            GITHUB_TOKEN: ${{ secrets.PAT }}
            GIT_COMMITTER_NAME: github-actions[bot]
            GIT_COMMITTER_EMAIL: github-actions[bot]@users.noreply.github.com
            GIT_AUTHOR_NAME: github-actions[bot]
            GIT_AUTHOR_EMAIL: github-actions[bot]@users.noreply.github.com

      - name: Update __about__
        if: steps.semantic.outputs.new_release_published == 'true'
        run: |
          npx semantic-release exec -- cmd /c "echo __version__ = '${{ steps.semantic.outputs.new_release_version }}' > __version__.py"
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add __version__.py
          git commit -m "chore: [gh] Update __version__.py to ${{ steps.semantic.outputs.new_release_version }}"
          git push https://${{ secrets.PAT }}@github.com/${{ github.repository }}.git HEAD:main
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}

      - name: Publish To GitHub Package Registry
        if: steps.semantic.outputs.new_release_published == 'true'
        run: echo "new release was published"
        shell: bash

      - name: Push updates to branch for major version
        if: steps.semantic.outputs.new_release_published == 'true'
        run: "git push https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git HEAD:refs/heads/v${{steps.semantic.outputs.new_release_major_version}}"
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
